# ingredient/ports.py
from typing import Iterable, Protocol
from domain.ingredient.model import Ingredient


class IngredientRepository(Protocol):
    def by_id(self, ingredient_id: str) -> Ingredient | None: ...
    def list_all(self) -> Iterable[Ingredient]: ...
    def save(self, ingredient: Ingredient) -> None: ...

# inventory/ports.py
from typing import Iterable, Protocol
from domain.inventory.model import InventoryItem


class InventoryRepository(Protocol):
    def by_id(self, item_id: str) -> InventoryItem | None: ...
    def list_all(self) -> Iterable[InventoryItem]: ...
    def save(self, item: InventoryItem) -> None: ...
    def delete(self, item_id: str) -> None: ...
